from __future__ import annotations

from app.schemas.agent_command import CommandType


GENERAL_COMMAND_TYPES = {
    CommandType.SHOW_HELP,
    CommandType.SHOW_SYSTEM_STATUS,
    CommandType.SHOW_OPERATIONS_STATUS,
    CommandType.SHOW_RISK_STATUS,
    CommandType.SHOW_BROKER_STATUS,
    CommandType.SHOW_SCHEDULER_STATUS,
    CommandType.SHOW_SETTINGS,
}

LOG_COMMAND_TYPES = {
    CommandType.SHOW_LOGS,
    CommandType.SHOW_RECENT_RUNS,
    CommandType.SHOW_RECENT_ORDERS,
    CommandType.SHOW_RECENT_SIGNALS,
}

ANALYSIS_COMMAND_TYPES = {
    CommandType.RUN_MARKET_ANALYSIS,
    CommandType.RUN_SINGLE_SYMBOL_ANALYSIS,
    CommandType.RUN_WATCHLIST_PREVIEW,
    CommandType.RUN_WATCHLIST_GPT_REVIEW,
    CommandType.SHOW_DECISION_REVIEW,
    CommandType.SHOW_OPERATOR_SUMMARY,
    CommandType.SHOW_CANDIDATE_DETAIL,
}

PORTFOLIO_COMMAND_TYPES = {
    CommandType.SHOW_PORTFOLIO,
    CommandType.SHOW_POSITIONS,
    CommandType.SHOW_POSITION_DETAIL,
    CommandType.REFRESH_BALANCE,
    CommandType.REFRESH_POSITIONS,
    CommandType.REFRESH_OPEN_ORDERS,
    CommandType.RUN_PORTFOLIO_REVIEW,
}

EXIT_COMMAND_TYPES = {
    CommandType.RUN_EXIT_PREFLIGHT,
    CommandType.RUN_EXIT_SHADOW_DECISION,
    CommandType.SHOW_EXIT_REVIEW,
    CommandType.SHOW_EXIT_REVIEW_QUEUE,
    CommandType.PREPARE_MANUAL_SELL_TICKET,
    CommandType.MARK_EXIT_QUEUE_REVIEWED,
    CommandType.DISMISS_EXIT_QUEUE_ITEM,
}

ORDER_COMMAND_TYPES = {
    CommandType.PREPARE_MANUAL_BUY_TICKET,
    CommandType.PREPARE_MANUAL_SELL_TICKET,
    CommandType.VALIDATE_MANUAL_ORDER,
    CommandType.REQUEST_LIVE_ORDER_SUBMIT,
    CommandType.CANCEL_MANUAL_ORDER_DRAFT,
    CommandType.SYNC_ORDER,
    CommandType.SYNC_OPEN_ORDERS,
}

SCHEDULER_COMMAND_TYPES = {
    CommandType.CREATE_ANALYSIS_SCHEDULE,
    CommandType.CREATE_EXIT_PREFLIGHT_SCHEDULE,
    CommandType.CREATE_WATCHLIST_PREVIEW_SCHEDULE,
    CommandType.SHOW_SCHEDULES,
    CommandType.CANCEL_SCHEDULE,
    CommandType.PAUSE_SCHEDULER,
    CommandType.RESUME_SCHEDULER,
    CommandType.REQUEST_LIVE_ORDER_SCHEDULE,
}

SETTING_COMMAND_TYPES = {
    CommandType.REQUEST_SETTING_CHANGE,
    CommandType.REQUEST_RISK_SETTING_CHANGE,
    CommandType.SET_DRY_RUN,
    CommandType.SET_KILL_SWITCH,
    CommandType.SET_BOT_ENABLED,
    CommandType.SET_SCHEDULER_ENABLED,
    CommandType.SET_DEFAULT_GATE_LEVEL,
    CommandType.SET_MAX_TRADES_PER_DAY,
    CommandType.SET_MAX_ORDER_SIZE,
    CommandType.SET_NO_NEW_ENTRY_AFTER,
    CommandType.SET_MAX_POSITION_SIZE,
    CommandType.SET_DAILY_LOSS_LIMIT,
    CommandType.SET_KIS_ENABLED,
    CommandType.SET_KIS_REAL_ORDER_ENABLED,
    CommandType.SET_KIS_SCHEDULER_ENABLED,
    CommandType.SET_KIS_SCHEDULER_REAL_ORDERS,
    CommandType.SET_KIS_LIMITED_AUTO_SELL,
    CommandType.SET_KIS_LIMITED_AUTO_BUY,
    CommandType.SET_KIS_LIVE_AUTO_BUY,
    CommandType.SET_KIS_LIVE_AUTO_SELL,
}

LIMITED_AUTO_COMMAND_TYPES = {
    CommandType.SHOW_LIMITED_AUTO_SELL_READINESS,
    CommandType.RUN_LIMITED_AUTO_SELL_REVIEW,
    CommandType.REQUEST_LIMITED_AUTO_SELL_ENABLE,
    CommandType.REQUEST_LIMITED_AUTO_SELL_DISABLE,
    CommandType.SHOW_LIMITED_AUTO_BUY_READINESS,
    CommandType.RUN_LIMITED_AUTO_BUY_REVIEW,
    CommandType.REQUEST_LIMITED_AUTO_BUY_ENABLE,
    CommandType.REQUEST_LIMITED_AUTO_BUY_DISABLE,
}

AGENT_COMMAND_TYPES = {
    CommandType.CREATE_AGENT_PLAN,
    CommandType.SHOW_AGENT_PLANS,
    CommandType.CANCEL_AGENT_PLAN,
    CommandType.UPDATE_AGENT_PLAN,
    CommandType.APPROVE_AGENT_PLAN,
    CommandType.REJECT_AGENT_PLAN,
}

READ_ONLY_WITHOUT_AUTH_COMMAND_TYPES = {
    CommandType.SHOW_SYSTEM_STATUS,
    CommandType.SHOW_OPERATIONS_STATUS,
    CommandType.SHOW_SETTINGS,
    CommandType.SHOW_LOGS,
    CommandType.SHOW_RECENT_RUNS,
    CommandType.SHOW_RECENT_ORDERS,
    CommandType.SHOW_RECENT_SIGNALS,
    CommandType.SHOW_PORTFOLIO,
    CommandType.SHOW_POSITIONS,
    CommandType.SHOW_BROKER_STATUS,
    CommandType.RUN_SINGLE_SYMBOL_ANALYSIS,
    CommandType.RUN_WATCHLIST_PREVIEW,
    CommandType.RUN_EXIT_PREFLIGHT,
}

LIVE_ORDER_COMMAND_TYPES = {
    CommandType.REQUEST_LIVE_ORDER_SUBMIT,
}

LIVE_ORDER_SCHEDULER_COMMAND_TYPES = {
    CommandType.REQUEST_LIVE_ORDER_SCHEDULE,
}

DANGEROUS_ENABLE_COMMAND_TYPES = {
    CommandType.REQUEST_LIMITED_AUTO_SELL_ENABLE,
    CommandType.REQUEST_LIMITED_AUTO_BUY_ENABLE,
    CommandType.SET_KIS_REAL_ORDER_ENABLED,
    CommandType.SET_KIS_SCHEDULER_REAL_ORDERS,
    CommandType.SET_KIS_LIVE_AUTO_BUY,
    CommandType.SET_KIS_LIVE_AUTO_SELL,
}

PREFILL_ONLY_COMMAND_TYPES = {
    CommandType.PREPARE_MANUAL_BUY_TICKET,
    CommandType.PREPARE_MANUAL_SELL_TICKET,
}

COMMAND_TYPE_VALUES = [command_type.value for command_type in CommandType]
