market: KR
currency: KRW
timezone: Asia/Seoul
symbols:
- symbol: 005930
  name: 삼성전자
  market: KOSPI
- symbol: '105560'
  name: KB금융
  market: KOSPI
- symbol: '000270'
  name: 기아
  market: KOSPI
- symbol: '034020'
  name: 두산에너빌리티
  market: KOSPI
- symbol: '055550'
  name: 신한지주
  market: KOSPI
- symbol: 068270
  name: 셀트리온
  market: KOSPI
- symbol: 086790
  name: 하나금융지주
  market: KOSPI
- symbol: '066570'
  name: LG전자
  market: KOSPI
- symbol: '035420'
  name: NAVER
  market: KOSPI
- symbol: '010120'
  name: LS ELECTRIC
  market: KOSPI
- symbol: '042660'
  name: 한화오션
  market: KOSPI
- symbol: '316140'
  name: 우리금융지주
  market: KOSPI
- symbol: '042700'
  name: 한미반도체
  market: KOSPI
- symbol: '015760'
  name: 한국전력
  market: KOSPI
- symbol: 096770
  name: SK이노베이션
  market: KOSPI
- symbol: 051910
  name: LG화학
  market: KOSPI
- symbol: '011200'
  name: HMM
  market: KOSPI
- symbol: '017670'
  name: SK텔레콤
  market: KOSPI
- symbol: '138040'
  name: 메리츠금융지주
  market: KOSPI
- symbol: '010140'
  name: 삼성중공업
  market: KOSPI
- symbol: 006800
  name: 미래에셋증권
  market: KOSPI
- symbol: 018260
  name: 삼성에스디에스
  market: KOSPI
- symbol: 033780
  name: KT&G
  market: KOSPI
- symbol: '035720'
  name: 카카오
  market: KOSPI
- symbol: '003550'
  name: LG
  market: KOSPI
- symbol: '267250'
  name: HD현대
  market: KOSPI
- symbol: 010950
  name: S-Oil
  market: KOSPI
- symbol: '064350'
  name: 현대로템
  market: KOSPI
- symbol: '024110'
  name: 기업은행
  market: KOSPI
- symbol: 086280
  name: 현대글로비스
  market: KOSPI
- symbol: '272210'
  name: 한화시스템
  market: KOSPI
- symbol: '003670'
  name: 포스코퓨처엠
  market: KOSPI
- symbol: '000720'
  name: 현대건설
  market: KOSPI
- symbol: '030200'
  name: KT
  market: KOSPI
- symbol: '071050'
  name: 한국금융지주
  market: KOSPI
- symbol: '323410'
  name: 카카오뱅크
  market: KOSPI
- symbol: 005940
  name: NH투자증권
  market: KOSPI
- symbol: '259960'
  name: 크래프톤
  market: KOSPI
- symbol: 005830
  name: DB손해보험
  market: KOSPI
- symbol: 078930
  name: GS
  market: KOSPI
- symbol: '196170'
  name: 알테오젠
  market: KOSDAQ
- symbol: 086520
  name: 에코프로
  market: KOSDAQ
- symbol: '247540'
  name: 에코프로비엠
  market: KOSDAQ
- symbol: 036930
  name: 주성엔지니어링
  market: KOSDAQ
- symbol: '240810'
  name: 원익IPS
  market: KOSDAQ
- symbol: 028300
  name: HLB
  market: KOSDAQ
- symbol: 058470
  name: 리노공업
  market: KOSDAQ
- symbol: '298380'
  name: 에이비엘바이오
  market: KOSDAQ
- symbol: 087010
  name: 펩트론
  market: KOSDAQ
- symbol: '000250'
  name: 삼천당제약
  market: KOSDAQ
