symbols:
  - NVDA
  - AAPL
  - MSFT
  - AMZN
  - GOOGL
  - GOOG
  - AVGO
  - META
  - TSLA
  - WMT
  - MU
  - AMD
  - ASML
  - COST
  - INTC
  - NFLX
  - CSCO
  - LRCX
  - PLTR
  - AMAT
  - TXN
  - KLAC
  - ARM
  - LIN
  - PEP
  - TMUS
  - ADI
  - AMGN
  - ISRG
  - GILD
  - SHOP
  - QCOM
  - APP
  - SNDK
  - BKNG
  - PANW
  - MRVL
  - PDD
  - WDC
  - HON
  - STX
  - SBUX
  - CRWD
  - VRTX
  - CEG
  - INTU
  - CMCSA
  - MAR
  - ADBE
  - SNPS