market: KR
currency: KRW
timezone: Asia/Seoul
symbols:
- symbol: '247540'
  name: 에코프로비엠
  market: KOSDAQ
- symbol: 086520
  name: 에코프로
  market: KOSDAQ
- symbol: '196170'
  name: 알테오젠
  market: KOSDAQ
- symbol: '277810'
  name: 레인보우로보틱스
  market: KOSDAQ
- symbol: 036930
  name: 주성엔지니어링
  market: KOSDAQ
- symbol: '000250'
  name: 삼천당제약
  market: KOSDAQ
- symbol: 058470
  name: 리노공업
  market: KOSDAQ
- symbol: 028300
  name: HLB
  market: KOSDAQ
- symbol: '298380'
  name: 에이비엘바이오
  market: KOSDAQ
- symbol: 039030
  name: 이오테크닉스
  market: KOSDAQ
- symbol: 087010
  name: 펩트론
  market: KOSDAQ
- symbol: '240810'
  name: 원익IPS
  market: KOSDAQ
- symbol: '440110'
  name: 파두
  market: KOSDAQ
- symbol: '141080'
  name: 리가켐바이오
  market: KOSDAQ
- symbol: 095340
  name: ISC
  market: KOSDAQ
- symbol: '222800'
  name: 심텍
  market: KOSDAQ
- symbol: '403870'
  name: HPSP
  market: KOSDAQ
- symbol: '214370'
  name: 케어젠
  market: KOSDAQ
- symbol: '310210'
  name: 보로노이
  market: KOSDAQ
- symbol: '178320'
  name: 서진시스템
  market: KOSDAQ
- symbol: '108490'
  name: 로보티즈
  market: KOSDAQ
- symbol: '319400'
  name: 현대무벡스
  market: KOSDAQ
- symbol: 080220
  name: 제주반도체
  market: KOSDAQ
- symbol: '010170'
  name: 대한광통신
  market: KOSDAQ
- symbol: '357780'
  name: 솔브레인
  market: KOSDAQ
- symbol: '067310'
  name: 하나마이크론
  market: KOSDAQ
- symbol: '319660'
  name: 피에스케이
  market: KOSDAQ
- symbol: 005290
  name: 동진쎄미켐
  market: KOSDAQ
- symbol: '064760'
  name: 티씨케이
  market: KOSDAQ
- symbol: 084370
  name: 유진테크
  market: KOSDAQ
