DEFAULT_TIMEFRAME = "1Min"
DEFAULT_BARS_LIMIT = 120

# Signal blending (quant-first)
QUANT_WEIGHT = 0.75
AI_WEIGHT = 0.25

# Candidate thresholds
BUY_QUANT_MIN = 60.0
BUY_AI_MIN = 55.0
BUY_FINAL_MIN = 65.0
SELL_QUANT_MIN = 60.0
SELL_AI_MIN = 55.0
SELL_FINAL_MIN = 65.0
MIN_BUY_SELL_SPREAD = 15.0

# Conservative risk defaults
MIN_CONFIDENCE_TO_TRADE = 0.65
MAX_TRADES_PER_DAY = 3
MAX_DAILY_LOSS_PCT = 0.02
BLOCK_NEAR_MARKET_CLOSE_DEFAULT = True
NEAR_CLOSE_MINUTES = 15
KILL_SWITCH_DEFAULT = False

# Position sizing defaults
WEAK_SETUP_POSITION_PCT = 0.05
DECENT_SETUP_POSITION_PCT = 0.07
STRONG_SETUP_POSITION_PCT = 0.10
MAX_POSITION_EQUITY_PCT = 0.10

SIGNAL_STATUS_CREATED = "created"
SIGNAL_STATUS_REJECTED = "rejected"
SIGNAL_STATUS_APPROVED = "approved"
SIGNAL_STATUS_EXECUTED = "executed"
SIGNAL_STATUS_SKIPPED = "skipped"
