DEFAULT_TIMEFRAME = "1Min"
DEFAULT_BARS_LIMIT = 120

# Conservative scoring thresholds
MIN_CONFIDENCE_TO_TRADE = 0.65
FINAL_SCORE_ACTION_THRESHOLD = 0.55
HOLD_SCORE_BAND = 0.08

# Quant / AI weighting
QUANT_WEIGHT = 0.8
AI_WEIGHT = 0.2

# Conservative risk defaults
MAX_TRADES_PER_DAY = 3
DEFAULT_POSITION_EQUITY_PCT = 0.05
MAX_POSITION_EQUITY_PCT = 0.10

# Placeholder runtime switches (DB/config can replace later)
KILL_SWITCH_DEFAULT = False
BLOCK_NEAR_MARKET_CLOSE_DEFAULT = True
NEAR_CLOSE_MINUTES = 15

SIGNAL_STATUS_CREATED = "created"
SIGNAL_STATUS_REJECTED = "rejected"
SIGNAL_STATUS_APPROVED = "approved"
SIGNAL_STATUS_EXECUTED = "executed"
SIGNAL_STATUS_SKIPPED = "skipped"