from enum import Enum


class InternalOrderStatus(str, Enum):
    REQUESTED = "REQUESTED"
    SUBMITTED = "SUBMITTED"
    ACCEPTED = "ACCEPTED"
    PENDING = "PENDING"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELED = "CANCELED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"
    UNKNOWN_STALE = "UNKNOWN_STALE"
    SYNC_FAILED = "SYNC_FAILED"
    REJECTED_BY_SAFETY_GATE = "REJECTED_BY_SAFETY_GATE"
    DRY_RUN_SIMULATED = "DRY_RUN_SIMULATED"
